### ISSUE TITLE
Convert gmsh to gitrm mesh with omega_h library converter

### ISSUE THREAD

**Issue by jguterl** [DIII-D/GITRmProject#11]
Check documentation here:
https://github.com/jguterl/pyGITRM/wiki/Install-omega_h-for-mesh-conversion
https://github.com/jguterl/pyGITRM/wiki/convert-gmsh-to-osh

**Comment by LC-GA** [comment]
Conversion completed! I have also written a little wiki: https://github.com/DIII-D/GITRmProject/wiki/Install-and-run-omega_h-mesh-converter

I'm closing this thread.
