### ISSUE TITLE
Add PEC for emission and SXB studies

### ISSUE THREAD

**Issue by LC-GA** [DIII-D/GITRmProject#19]
Adding PEC emission coefficients and a way to discriminate W^+1 emission could allow us to make predictions regarding UV measures of "net erosion"

**Comment by jguterl** [comment]
1) add adf15 to ADAS.jl
2) look up ERO src code guterl version to look for emission accumulation
(integrale along trajectory)

**Comment by LC-GA** [comment]
discretize z axis to infer W density profile perpendicular to material, apply PEC to retrieve line of sight signal

**Comment by LC-GA** [comment]
ADAS package updated to retrieve adf15 files, workflow established to connect ADAS to LPTMC.
