### ISSUE TITLE
check PEC for W lines seen by Ulises

### ISSUE THREAD

**Issue by LC-GA** [DIII-D/GITRmProject#21]
WII line: 265.8 nm         

WI main line: 255.13 nm

Ask Auburn if they can calculate PEC for these 2 lines if missing from ADAS

**Comment by jguterl** [comment]
what is the answer?

**Comment by LC-GA** [comment]
ADAS PEC files don't contain Ulises lines, not even the 400.9 nm W line. Proper PEC files will be delivered by Auburn experts.

**Comment by jguterl** [comment]
Make another issue to keep track of getting correct files
