### ISSUE TITLE
Install and use VScode

### ISSUE THREAD

**Issue by jguterl** [DIII-D/GITRmProject#3]
Install Vscode on laptop

**Comment by jguterl** [comment]
connect to omega through ssh remote connection

**Comment by LC-GA** [comment]
VS was installed with the Remote - SSH extension. The connection to cybele was successful.

**Comment by jguterl** [comment]
to pipe omega thorugh cybele, add the following line in a ssh/config file
(instruction here:
https://superuser.com/questions/1537763/location-of-openssh-configuration-file-on-windows)

Host omega.gat.com
HostName omega.gat.com
User guterlj
ProxyCommand ssh -p 2039 ***@***.*** nc %h %p 2> /dev/null

**Comment by jguterl** [comment]
also copy ssh key on both cybele and omega to access it without typing
password
